


# ===================================================================
# Spring Boot configuration for the Grouse
#
# Set to require MySQL in production
# ===================================================================

server:
  application:
    name: KDRS-SA Grouse (Demo mode)
  servlet:
    context-path: /grouse
  port: 9294

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kravspec
    username: INSERT-USERNAME-HERE
    password: INSERT-PASSWORD-HERE
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: db/import.sql,db/functionality.sql,db/requirements.sql
        show_sql: true
        hbm2ddl.auto: create-drop

storage:
  location: /var/grouse/storage
