package no.kdrs.grouse.kravspec;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import no.kdrs.grouse.kravspec.KravspecUser;
import no.kdrs.grouse.kravspec.KravspecUserRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/kravspec") // This means URL's start with /kravspec (after Application path)
public class KravspecMainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private KravspecUserRepository userRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name
						, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		KravspecUser n = new KravspecUser();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<KravspecUser> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
